### ISSUE TITLE
The ClassCastException in process of a Hibernate Proxy mapping

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vadbch/orika#118]
```
What steps will reproduce the problem?
1. Perform attached test case.

What is the expected output? What do you see instead?
The ClassCastException are happenned instead of executing without error

What version of the product are you using? On what operating system?
Orika 1.4.3, hibernate 4.2.4, spring 3.1.3, JDK7, Win 7.

Please provide any additional information below.
If you change 91 line of OrikaHibernateInheritanceTest.java from 
    PersonEntity peter = (PersonEntity) getSession().load(PersonEntity.class, peterId);
to
    PersonEntity peter = (PersonEntity) getSession().get(PersonEntity.class, peterId);
a hibernate proxy will not be created and the test will be passed.


Stacktrace is attached.
```

Original issue reported on code.google.com by `kasi...@gmail.com` on 20 Aug 2013 at 9:23

Attachments:
- [testCase.zip](https://storage.googleapis.com/google-code-attachments/orika/issue-118/comment-0/testCase.zip)

**Comment by GoogleCodeExporter** [comment]
```
The test passes, can not reproduce.
I run the test with provided versions still the test pass.

14:47:47.056 [main] DEBUG m.g.orika.impl.MapperFacadeImpl - MappingStrategy 
resolved and cached:
    Inputs:[ sourceClass: com.bftcom.qdp.server.orika.inheritance.OwnerEntity_$$_javassist_0, sourceType: PersonEntity, destinationType: PersonDto]
    Resolved:[ strategy: InstantiateAndUseCustomMapperStrategy, sourceType: OwnerEntity, destinationType: OwnerDto, mapper: GeneratedMapper(OwnerEntity, OwnerDto), mapReverse?: false]
14:47:47.058 [main] DEBUG m.g.orika.impl.MapperFacadeImpl - MappingStrategy 
resolved and cached:
    Inputs:[ sourceClass: com.bftcom.qdp.server.orika.inheritance.PersonEntity_$$_javassist_2, sourceType: PersonEntity, destinationType: PersonDto]
    Resolved:[ strategy: InstantiateAndUseCustomMapperStrategy, sourceType: PersonEntity, destinationType: PersonDto, mapper: GeneratedMapper(PersonEntity, PersonDto), mapReverse?: false]

```

Original comment by `elaat...@gmail.com` on 20 Aug 2013 at 12:51

**Comment by GoogleCodeExporter** [comment]
```
I'm so sorry. I've made a mistake.
Please, change 91 line of OrikaHibernateInheritanceTest.java from  
  PersonEntity peter = (PersonEntity) getSession().get(PersonEntity.class, peterId);
to
  PersonEntity peter = (PersonEntity) getSession().load(PersonEntity.class, peterId);

calling "get" method is condition for passing test.
```

Original comment by `kasi...@gmail.com` on 20 Aug 2013 at 3:16

**Comment by GoogleCodeExporter** [comment]
```
Yes I see what you want to test (proxies management), even with .load (which 
return a proxy) the test passes, please you can also refer to this unit test. 
this is part of unit tests:

https://github.com/orika-mapper/orika/blob/master/tests/src/main/java/ma/glasnos
t/orika/test/unenhance/inheritance/HibernateProxyTestCase.java

Please let me know if they are the same.
```

Original comment by `elaat...@gmail.com` on 20 Aug 2013 at 4:32

**Comment by GoogleCodeExporter** [comment]
```
I turn all session.get to session.load still the test passes.

Here is another one:
https://github.com/orika-mapper/orika/blob/master/tests/src/main/java/ma/glasnos
t/orika/test/unenhance/HibernateProxyTestCase.java
```

Original comment by `elaat...@gmail.com` on 20 Aug 2013 at 4:35

**Comment by GoogleCodeExporter** [comment]
```
I've pulled request https://github.com/orika-mapper/orika/pull/16 with my test 
case. It fails every time on the master.
```

Original comment by `kasi...@gmail.com` on 21 Aug 2013 at 9:41

**Comment by GoogleCodeExporter** [comment]
```
Yes!
The Travis CI build failed with my commit.
https://travis-ci.org/orika-mapper/orika/builds/10444806

Caused by: java.lang.ClassCastException: 
ma.glasnost.orika.test.unenhance.inheritance2.PersonEntity_$$_javassist_9 
cannot be cast to ma.glasnost.orika.test.unenhance.inheritance2.OwnerEntity
    at ma.glasnost.orika.generated.Orika_OwnerDto_OwnerEntity_Mapper259962291302$865.mapAtoB(Orika_OwnerDto_OwnerEntity_Mapper259962291302$865.java:11)
    at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:65)
    at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:645)
    at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsSet(MapperFacadeImpl.java:391)
    at ma.glasnost.orika.generated.Orika_RoomDto_RoomEntity_Mapper259939629332$864.mapAtoB(Orika_RoomDto_RoomEntity_Mapper259939629332$864.java:19)
    at ma.glasnost.orika.impl.mapping.strategy.UseCustomMapperStrategy.map(UseCustomMapperStrategy.java:65)
    at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:694)
    ... 37 more
```

Original comment by `kasi...@gmail.com` on 21 Aug 2013 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
Thanks :) I will digg at the issue and keep you informed on the progress. 
On Jenkins it fails also.

```

Original comment by `elaat...@gmail.com` on 21 Aug 2013 at 10:15

**Comment by GoogleCodeExporter** [comment]
```
Sorry for the late reply.

In the process of outboxing proxied objects. Orika record a strategy for all 
elements of collection.  
in the recording data  there is flag to use or not unenhanceObject (for 
performance).

In your test you load the first one by get owner and the second by load, in the 
first there is no proxy and  proxied one for the second. This kind of thing  (I 
suppose) should not happen.

You can also if you want disable this kind of optimizations. But you can lost 
on performance.
```

Original comment by `elaat...@gmail.com` on 25 Aug 2013 at 10:43

**Comment by GoogleCodeExporter** [comment]
```
We've met it in our real project. Do you decide fix it?
```

Original comment by `kasi...@gmail.com` on 26 Aug 2013 at 8:00

**Comment by GoogleCodeExporter** [comment]
```
Of course.

```

Original comment by `elaat...@gmail.com` on 26 Aug 2013 at 9:10
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
A fix has been commited to master repo. 
Please confirm.
```

Original comment by `elaat...@gmail.com` on 28 Aug 2013 at 7:39
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Perfect! Thanks!
We are waiting a new release :)
```

Original comment by `kasi...@gmail.com` on 29 Aug 2013 at 9:51
