### ISSUE TITLE
Compilation Error when referencing collection on class property

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vadbch/orika#141]
```
From Eddie G on the group thread:

I believe I may have found a bug around accessing collections on a class's 
property.

I have a mapping that looks like this....
        mapperFactory.classMap(Clazz.class, Clazz2.class)
                .field("subClass.strings[0]", "string")
                .register();

This mapping works fine if I have .field("strings[0]", "string"), however I get 
a compilation error with the subClass present, like in the example above.

I have attached a test case for this as well.

Is this a legit bug?


```

Original issue reported on code.google.com by `matt.deb...@gmail.com` on 21 Dec 2013 at 12:41

Attachments:
- [CollectionsOnClassPropertyTest.java](https://storage.googleapis.com/google-code-attachments/orika/issue-141/comment-0/CollectionsOnClassPropertyTest.java)

**Comment by GoogleCodeExporter** [comment]
```
Additionally, from Chris C on the thread:

I ran into this while trying to map a DTO to a JAXB generated class. Orika 
appears to stop one level short when resolving the destination and is treating 
a non-list field as a list. The following code replicates the issue.  This is 
my first time using Orika and most likely I'm missing something, but any 
assistance is definitely appreciated.  Tried on Orika 1.4.2 and 1.4.3


The exception thrown is:

javassist.CannotCompileException: [source error] add(int,java.lang.String) not 
found in test.factory.D
    at javassist.CtNewMethod.make(CtNewMethod.java:79)
    at javassist.CtNewMethod.make(CtNewMethod.java:45)
    at ma.glasnost.orika.impl.generator.JavassistCompilerStrategy.compileClass(JavassistCompilerStrategy.java:251)
    at ma.glasnost.orika.impl.generator.SourceCodeContext.compileClass(SourceCodeContext.java:234)
    at ma.glasnost.orika.impl.generator.SourceCodeContext.getInstance(SourceCodeContext.java:251)
    at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:74)
    at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1139)
 ...


The generated code shows an instance of D being accessed as a List<String>

((test.factory.D)((test.factory.C)((java.util.List)((test.factory.B)destination.
getB()).getC()).get(0)).getD()).add(0, ((java.lang.String)source.getData()));


MapperFactory mapperFactory = new DefaultMapperFactory.Builder()
            .useAutoMapping(false)
            .mapNulls(false)
            .build();

           mapperFactory.classMap(TheBean.class, A.class)
            .field("data", "b.c[0].d.data[0]")
            .register();

        MapperFacade mapper = mapperFactory.getMapperFacade();


        TheBean theBean = new TheBean();
        theBean.setData("TEST");

        A a = mapper.map(theBean, A.class);


public class A{
    private B b = new B();

    public B getB() { return b; }

    public void setB(B b) { this.b = b; }   
}

public class B{
    private List<C> c = new ArrayList<C>();

    public List<C> getC() { return c; }

    public void setC(List<C> c) { this.c = c; }
}

public class C{
    private D d = new D();

    public D getD() { return d; }

    public void setD(D d) { this.d = d; }
}

public class D{
    private List<String> data = new ArrayList<String>();

    public List<String> getData() { return data; }

    public void setData(List<String> data) { this.data = data; }
}

public class TheBean{
    private String data;

    public String getData() { return data; }

    public void setData(String data) { this.data = data; }
}
```

Original comment by `matt.deb...@gmail.com` on 21 Dec 2013 at 12:42

**Comment by GoogleCodeExporter** [comment]
```
A fix has been pushed to the current master; please check it out.
```

Original comment by `matt.deb...@gmail.com` on 23 Dec 2013 at 9:23
