### ISSUE TITLE
NPE when mapping a class implementing a map

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vadbch/orika#92]
```
What steps will reproduce the problem?
Given a class A extending AbstractMap with a custom field "id",
try to map "id" to a field of another class B (not extending AbstractMap)


What is the expected output? What do you see instead?
A new instance of B. Got instead

Caused by: java.lang.NullPointerException: null
        at ma.glasnost.orika.metadata.Property.<init>(Property.java:56) ~[orika-core-1.4.1.jar:na]
        at ma.glasnost.orika.metadata.MapKeyProperty.<init>(MapKeyProperty.java:30) ~[orika-core-1.4.1.jar:na]
        at ma.glasnost.orika.metadata.ClassMapBuilderForMaps.resolveCustomProperty(ClassMapBuilderForMaps.java:161) ~[or
ika-core-1.4.1.jar:na]
        at ma.glasnost.orika.metadata.ClassMapBuilderForMaps.resolveProperty(ClassMapBuilderForMaps.java:154) ~[orika-co
re-1.4.1.jar:na]
        at ma.glasnost.orika.metadata.FieldMapBuilder.<init>(FieldMapBuilder.java:78) ~[orika-core-1.4.1.jar:na]
        at ma.glasnost.orika.metadata.FieldMapBuilder.<init>(FieldMapBuilder.java:61) ~[orika-core-1.4.1.jar:na]
        at ma.glasnost.orika.metadata.ClassMapBuilder.fieldMap(ClassMapBuilder.java:229) ~[orika-core-1.4.1.jar:na]
        at ma.glasnost.orika.metadata.ClassMapBuilderForMaps.fieldMap(ClassMapBuilderForMaps.java:139) ~[orika-core-1.4.
1.jar:na]
        at ma.glasnost.orika.metadata.ClassMapBuilder.fieldMap(ClassMapBuilder.java:215) ~[orika-core-1.4.1.jar:na]
        at ma.glasnost.orika.metadata.ClassMapBuilder.field(ClassMapBuilder.java:159) ~[orika-core-1.4.1.jar:na]

What version of the product are you using? On what operating system?
Orika version 1.4.1

Please provide any additional information below.
```

Original issue reported on code.google.com by `fago.ma...@gmail.com` on 27 Mar 2013 at 10:11

**Comment by GoogleCodeExporter** [comment]
```
The NullPointerException will be fixed (and report a better error message) when 
1.4.2 released.
But still there is a need for generics type information.
Can you please provide us with a concrete Unit test.
```

Original comment by `elaat...@gmail.com` on 27 Mar 2013 at 10:33

**Comment by GoogleCodeExporter** [comment]
```
Unit test attached.
```

Original comment by `fago.ma...@gmail.com` on 27 Mar 2013 at 2:35

Attachments:
- [MapClassTest.java](https://storage.googleapis.com/google-code-attachments/orika/issue-92/comment-2/MapClassTest.java)

**Comment by GoogleCodeExporter** [comment]
```
A fix for this has been applied to the current master (1.4.3-SNAPSHOT).
Please take a look...
```

Original comment by `matt.deb...@gmail.com` on 30 May 2013 at 7:35

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.deb...@gmail.com` on 30 May 2013 at 7:35
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
I switched to 1.4.3 and removed my patch, and it works.
Thank you.
```

Original comment by `fago.ma...@gmail.com` on 26 Jun 2013 at 7:36

**Comment by GoogleCodeExporter** [comment]
Original comment by `matt.deb...@gmail.com` on 27 Jun 2013 at 6:25
- Changed state: **Fixed**
